Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # CONTROL PLANE
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.10"

    master.vm.provision "shell", path: "provisioning/common.sh"
    master.vm.provision "shell", path: "provisioning/master.sh"
  end

  # WORKER NODE
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.56.11"

    worker.vm.provision "shell", path: "provisioning/common.sh"
    worker.vm.provision "shell", path: "provisioning/worker.sh"
  end
end