Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64" # Ubuntu 22.04.5 LTS (Jammy Jellyfish)
  config.vm.synced_folder "provisioning", "/vagrant", create: true
  
  config.vm.provision "ansible_local", run: "always" do |ansible|
    ansible.become = true
    ansible.playbook = "/vagrant/install_software.yml"
    ansible.install = true
  end  

   config.vm.network "private_network", ip:"192.168.33.10"
   config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
   end
   
end