Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Common settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # WEB SERVER
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.10"

    web.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provisioning/site.yml"
      ansible.inventory_path = "provisioning/inventory.ini"
      ansible.limit = "web"
    end
  end

  # DB SERVER
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.33.11"

    db.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provisioning/site.yml"
      ansible.inventory_path = "provisioning/inventory.ini"
      ansible.limit = "db"
    end
  end
end